### ISSUE TITLE
Not working on macOS - (FileNotFoundError)

### ISSUE THREAD

**Issue by nurb2kea** [strike-digital/node_pie#1]
Hi,

I'm on macOS 12.5.1 and blender 3.1 to 3.4.
I get the following error message in all versions and see only the center circle from the pie menu & nothing else.
Also I instal add-ons via Target Path -> Preferences.
![Screen Shot 2022-08-25 at 3 13 53 am](https://user-images.githubusercontent.com/57676085/186552026-f726a705-b9c4-4752-938a-cefbbe5d9169.jpg)

![Screen Shot 2022-08-25 at 3 17 08 am](https://user-images.githubusercontent.com/57676085/186552246-70c12971-84f2-4dbb-9a6d-90ddd5f93363.jpg)

The thing is there is no such nodes.json file in this folder, on this git page and its download. Nor is it in the blender dir.

Python: Traceback (most recent call last):
  File "/Applications/BLENDER/ADDONS etc/addons/node_pie-main/node_pie/npie_ui.py", line 109, in draw
    node_count_data = get_all_node_data()["node_trees"].get(tree_type, {})
  File "/Applications/BLENDER/ADDONS etc/addons/node_pie-main/node_pie/npie_ui.py", line 13, in get_all_node_data
    with open(Path(__file__).parent / "nodes.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/BLENDER/ADDONS etc/addons/node_pie-main/node_pie/nodes.json'

Thanks in advance

SG

**Comment by xan2622** [comment]
Same error on Windows 11.

On Blender 3.2.2, with Node Pie Menu 1.0.0, when I press CTRL + LMB, I get this error: 

```
Traceback (most recent call last):
  File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\node_pie-main\node_pie\npie_ui.py", line 109, in draw
    node_count_data = get_all_node_data()["node_trees"].get(tree_type, {})
  File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\node_pie-main\node_pie\npie_ui.py", line 13, in get_all_node_data
    with open(Path(__file__).parent / "nodes.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xan2622\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons\\node_pie-main\\node_pie\\nodes.json'
```

**Comment by strike-digital** [comment]
Thanks for reporting this, I've uploaded a new version which should fix it :)

**Comment by nurb2kea** [comment]
Perfect, works like a charme.
Thanks you very much. :-)

**Comment by strike-digital** [comment]
Great, glad it's working now!
