### ISSUE TITLE
Blender 3.5 Nothing can be seen in the Geometry Node Editor

### ISSUE THREAD

**Issue by LadyCuaCua** [strike-digital/node_pie#11]
Excuse me, sir. I hope to receive some assistance
![image](https://user-images.githubusercontent.com/38346302/230627561-299ddefd-ff7f-46ca-b4bd-a2e4017d95bb.png)

In shading, it is working！

**Comment by strike-digital** [comment]
Hi, sorry for the wait, this is due to the way the add menu is created changing in 3.5 quite drastically, which breaks node pie.

I do have some ideas for how to fix it, but I'm pretty busy currently, so it might have to wait for a while before I can get around to working on it.

**Comment by LadyCuaCua** [comment]
😀I'm glad to see your reply and hope your work goes smoothly. I will wait patiently for you to solve the addon issue👌

**Comment by strike-digital** [comment]
Hi, sorry it took a while, I've just uploaded a new release, the addon should now work properly in 3.5, 3.6 and 4.0 :)
