### ISSUE TITLE
Looking forward to your fixing "ShaderNodeMix" under color in blender3.5 as color mixing

### ISSUE THREAD

**Issue by chenpaner** [strike-digital/node_pie#12]
bpy.ops.node.add_node(type="ShaderNodeMix", use_transform=True, settings=[{"name":"data_type", "value":"'RGBA'"}])

Thank you very much for making and sharing this plugin for free. I know you are busy with work. I hope you can fix this small problem when you are free. I wish you a happy work!

**Comment by strike-digital** [comment]
Hi, sorry for the wait, this should be fixed in the latest release (at least in Blender versions 3.5 - 4.0) :)
