### ISSUE TITLE
NodePie 1.2.7 and blender 4.0 aren't best friends...

### ISSUE THREAD

**Issue by nurb2kea** [strike-digital/node_pie#13]
Pie menu not coming up anymore in 4.0

https://wiki.blender.org/wiki/Reference/Release_Notes/4.0/Python_API

![Screenshot 2023-05-31 at 2 36 39 pm](https://github.com/strike-digital/node_pie/assets/57676085/0d4b4f57-baf1-431e-91e4-4cd55dde828c)

**Comment by strike-digital** [comment]
Hi, sorry for the wait, I've been away from my computer for a while.

I've just uploaded a new release, so it should now work with both 3.6 and 4.0 :)

**Comment by nurb2kea** [comment]
Hi, sorry to say but it's not working with any MacOS blender version. I tried from 3.1 to 4.0 MacOS !
It installs and registers the addon (see image) but nothing is displayed when using the mouse or shortcut keys,
even when changed.

I guess it's again a MacOS problem.
Maybe is still related to what I posted before, but I'm not sure !!

The blender dev’s reccomended to ask [https://projects.blender.org/mano-wii ](https://projects.blender.org/mano-wii)
and look at this case to get more info on this to fix addons.

EDIT: More info !

There are two reasons why shaders needs to be ported:

Addon still uses bgl that call OpenGL calls directly.
Shader don’t use gpu.types.ShaderCreateInfo to support cross platform source generation.
These structures have already been in place for some time, and we communicated that addon developers should use this new API. It is sadly common for developers to only port to newer API’s when it makes sense for them.

In this case it looks like he hasn’t ported his shaders to use gpu.types.ShaderCreateInfo as described on [https://docs.blender.org/api/current/gpu.html 2](https://docs.blender.org/api/current/gpu.html). If someone requires some help they can get in contact with the Eevee/viewport module at blender.chat or in the python channel. I am happy to help out there.

![Screenshot 2023-06-16 at 10 28 15 pm](https://github.com/strike-digital/node_pie/assets/57676085/7bd5b7ec-add7-4ffe-9c1d-0154a62aeb13)

**Comment by strike-digital** [comment]
Huh, that's really weird, just to check, is anything printed to the terminal when you try and call the pie menu (I think on Mac you have to launch blender from the terminal to be able to see the output)?

It shouldn't have anything to do with shaders as I thought I disabled everything in there to do with that before uploading, but maybe something slipped through...

Can you try this version, and see if it works:
[node_pie_1_2_9.zip](https://github.com/strike-digital/node_pie/files/11776768/node_pie_1_2_9.zip)

Thanks!

**Comment by nurb2kea** [comment]
Nope, nothing in the terminal about node_pie for both 1.2.8 & 1.2.9.

**Comment by strike-digital** [comment]
Weird...

Can you try using the operator search to find it, and see if it works when calling it from there?

**Comment by strike-digital** [comment]
Ok, next attempt, I'm quietly confident about this one 😅

[node_pie_1_2_9.zip](https://github.com/strike-digital/node_pie/files/11778882/node_pie_1_2_9.zip)

**Comment by nurb2kea** [comment]
![Screenshot 2023-05-25 at 1 55 54 pm](https://github.com/strike-digital/node_pie/assets/57676085/82acae12-98ce-4a76-8357-20f6558f9498)

**Comment by nurb2kea** [comment]
That last change was successful. I guess this changes will apply to all your addons like mini map etc...

Anyways, a big thank you for your support and effort ! 🙂

**Comment by strike-digital** [comment]
Amazing! It's so nice to finally have a working solution to this 😅
