### ISSUE TITLE
Node pie 1.2.8 Shortcut issue

### ISSUE THREAD

**Issue by hokutonanto** [strike-digital/node_pie#14]
Hi,

In the previous version, I was able to assign a custom shortcut from Blender's Key map preferences. It seems in the latest 1.2.8 I'm not able to assign it anymore.

Changing the existing shortcut in the add-on preferences, or creating a new one, has no effect.

Is there a workaround?

Thanks

**Comment by strike-digital** [comment]
Hi, should be fixed in the latest release, can you try it and confirm that it's working? Thanks!

**Comment by hokutonanto** [comment]
Thanks!
