### ISSUE TITLE
Blender 4.0 and MacOS issue

### ISSUE THREAD

**Issue by nurb2kea** [strike-digital/node_pie#15]
Hi, 

here a new issue with the upddate on MacOS.

![Screenshot 2023-06-25 at 7 11 54 pm](https://github.com/strike-digital/node_pie/assets/57676085/53d36dc3-37d5-4a38-a710-3654924b6dca)

![Screenshot 2023-06-25 at 7 14 47 pm](https://github.com/strike-digital/node_pie/assets/57676085/4663bcb8-1150-46ff-95a8-23b1668acfe2)

![SYSTEM](https://github.com/strike-digital/node_pie/assets/57676085/0da3f85a-047d-42d8-bc33-9f3622b1f5f8)

**Comment by strike-digital** [comment]
Ah, thanks for reporting that, should be fixed in the latest release :)

**Comment by strike-digital** [comment]
Ah, my mistake, I forgot to update the build before uploading it, I've updated the release, so hopefully it works now.

**Comment by nurb2kea** [comment]
Hi, yepp seems to work now.

Thank you very much! :-))

![Screenshot 2023-06-27 at 2 20 12 pm](https://github.com/strike-digital/node_pie/assets/57676085/a6ee6ed5-bbac-467d-9329-ac7cd0ba9c72)

**Comment by strike-digital** [comment]
Great!
