### ISSUE TITLE
An excellent plugin

### ISSUE THREAD

**Issue by NewTypo** [strike-digital/node_pie#16]
Hairline a bug Not sure if it's a blender problem.

![2023-06-27_18-40](https://github.com/strike-digital/node_pie/assets/17538796/bcbd1f1f-a361-42ac-88fc-7b377da253be)

At the same time, there is a suggestion, can it be adapted to the small screen computer?

![2023-06-27_18-44](https://github.com/strike-digital/node_pie/assets/17538796/685d53b2-89b5-4d48-be3a-41b5a89bbb7a)

**Comment by strike-digital** [comment]
Hi, thanks for reporting this, I've uploaded a new release, so it should be fixed in 4.0 now :)

As for it being too big, you can change the size of the buttons in the preferences:
![image](https://github.com/strike-digital/node_pie/assets/59890307/3207b9ed-9468-40a3-86d9-189f96c3e569)

**Comment by NewTypo** [comment]
Ok thank you
