### ISSUE TITLE
Bug feedback

### ISSUE THREAD

**Issue by NewTypo** [strike-digital/node_pie#17]
![image](https://github.com/strike-digital/node_pie/assets/17538796/2ec94cda-355c-485f-996e-22acd8a5ee43)

After installing the latest version, an error is reported, I don't know what the reason is

**Comment by strike-digital** [comment]
That's odd, I think I've found the problem, but I'm not entirely sure, could you try this version and see if it works:

[node_pie_1_2_14.zip](https://github.com/strike-digital/node_pie/files/11993681/node_pie_1_2_14.zip)

Thanks!

**Comment by NewTypo** [comment]
Perfectly solved the problem, thank you for developing such a great plugin.
