### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xboxcopy** [strike-digital/node_pie#19]
when there is a socket that not connected to any node, bring up the pie menu gives error message.
![2023-07-12 20_55_00-Blender](https://github.com/strike-digital/node_pie/assets/26083237/1a2ccedb-5e6a-417a-9961-95ea7dbb2a82)

**Comment by strike-digital** [comment]
Hi, thanks for reporting this, I've updated the release, so if you redownload it, it should work now :)
