### ISSUE TITLE
Can't Install!

### ISSUE THREAD

**Issue by FidoAnh** [strike-digital/node_pie#2]
I can't install
Traceback (most recent call last):
  File "/home/fidotran/FidoSoftware/Blender/3.2/scripts/modules/addon_utils.py", line 335, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'node_pie-1.0'

**Comment by FidoAnh** [comment]
I'm on linux

**Comment by strike-digital** [comment]
Hi, Is there any more that is printed before the error you pasted?

**Comment by FidoAnh** [comment]
I'm install again an this is what printed from I install zip file
Info: Updated sidebar tabs
addon_utils.disable: node_pie-1.0.0 not disabled
Modules Installed (node_pie-1.0.0) from '/home/fidotran/Downloads/node_pie-1.0.0.zip' into '/home/fidotran/.config/blender/3.2/scripts/addons'
Traceback (most recent call last):
  File "/home/fidotran/FidoSoftware/Blender/3.2/scripts/modules/addon_utils.py", line 335, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'node_pie-1'

**Comment by strike-digital** [comment]
Ok, I think that's caused because the name of the zip file created by Github had multiple "." characters in it which probably confused Blender somewhere. I've updated the release with a proper zip, so it should hopefully work for you if you download that version.

**Comment by FidoAnh** [comment]
Thank you! It's work perfect!
