### ISSUE TITLE
Reroute dot node causes error messages coming up.

### ISSUE THREAD

**Issue by nurb2kea** [strike-digital/node_pie#20]
Hi,

- with just a cube in the scene, when in shader, geometry, compositor node editors without anything in it and dial the node pie you get a message. If a new material or use nodes is clicked node pie works fine.

-  in shader, geometry, compositor node editors maybe some nodes or nodegroups make trouble & some are not. 
I'm not able to figure it out completely what is wrong there. But you also get a message.

**At least I found out that the 'Reroute' node (dot) is causing trouble. see images**

- this happens with blender 3.1 up to 3.6.1 & 4.0alpha + node pie 1.2.16

![Screenshot 2023-07-13 at 12 49 53 pm](https://github.com/strike-digital/node_pie/assets/57676085/85adc468-a95f-4198-98db-991deb181e94)
![Screenshot 2023-07-13 at 12 50 26 pm](https://github.com/strike-digital/node_pie/assets/57676085/5a46246e-b25d-4bf4-a07b-d18af0287b61)
![Screenshot 2023-07-13 at 12 50 54 pm](https://github.com/strike-digital/node_pie/assets/57676085/aa646ce7-ac49-42b0-808a-744d74eb9341)

![Screenshot 2023-07-13 at 1 22 17 pm](https://github.com/strike-digital/node_pie/assets/57676085/1726b5cb-3d7e-4a8a-8ce0-5ac27aa27e49)
![Screenshot 2023-07-13 at 1 22 58 pm](https://github.com/strike-digital/node_pie/assets/57676085/e9076b4a-365e-412f-b8a3-47035a2a6665)

**Comment by strike-digital** [comment]
Ah, thanks for finding that, I've updated the release, so it should be fixed now :)

**Comment by nurb2kea** [comment]
Bingo, that fixed it. And very quick as well!! :-))
Thanks. 👍

**Comment by strike-digital** [comment]
Great, glad it's working!
