### ISSUE TITLE
Shader compile error

### ISSUE THREAD

**Issue by nurb2kea** [strike-digital/node_pie#21]
Intel MacOS, blender 3.6.1, node pie 1.2.18

![Screenshot 2023-07-24 at 12 48 17 pm](https://github.com/strike-digital/node_pie/assets/57676085/9da6a286-fea4-4fce-9d0f-8746b6472586)

**Comment by strike-digital** [comment]
That's weird, can you look in the console when you try and enable the addon, and see what extra errors are printed there (you might have to scroll up quite a bit).

**Comment by nurb2kea** [comment]
No that is all ! 
![Screenshot 2023-07-24 at 3 15 41 pm](https://github.com/strike-digital/node_pie/assets/57676085/8aa44fb7-9e36-4a15-8b1a-417ee3c5f8bc)

**Comment by strike-digital** [comment]
Ok, can you try this version:
[node_pie_1_2_19.zip](https://github.com/strike-digital/node_pie/files/12152313/node_pie_1_2_19.zip)

I'm not entirely sure that it will work, but fingers crossed 🤞

**Comment by nurb2kea** [comment]
Getting there... :-)
![Screenshot 2023-07-25 at 1 03 23 am](https://github.com/strike-digital/node_pie/assets/57676085/5895324b-c5e3-4106-8e80-f39d877f20b1)

**Comment by nurb2kea** [comment]
Still not working with node_pie_1_2_19.zip !?
See message above.

**Comment by strike-digital** [comment]
Oh, sorry for not replying, for some reason I didn't see your last message. Does it still not show any more info in the terminal if you start Blender from there?

**Comment by nurb2kea** [comment]
Yes, that's the reason wrote.
As you can see the in the first screenshot it's line 13 and in the second screenshot it's line 32 of the npie_drawing.py file after I used node_pie_1_2_19.zip.

**Comment by strike-digital** [comment]
Hmm, the reason I ask is that if there's a Shader compile error, for me, it gets printed above the addon enable error, and it makes it much easier to figure out what's going wrong. I was fairly certain I knew what was causing it, but since that's not fixed it, I'm a little bit stumped...

There seems to be very little information online about this kind of problem, and unfortunately I don't have access to any Apple device that I could use to test on, so unfortunately I may not be able to fix this one without knowing the compile error that's causing it.

Sorry to disappoint :(

**Comment by nurb2kea** [comment]
Hi, just an update on the latest version of blender 3.6.6 &4.0b. 
Maybe there is a solution. I recommended to other addon devs to run a free Virtual machine (virtual box for example) and MacOS and Linux to test their builds, what worked fine.

I understood you last post. So this post is just an info for you. 
 
![Screenshot 2023-11-10 at 5 13 26 pm](https://github.com/strike-digital/node_pie/assets/57676085/b2dfa1c8-e3df-4a4c-88a7-17cb15326688)
![Screenshot 2023-11-10 at 5 12 48 pm](https://github.com/strike-digital/node_pie/assets/57676085/3a8ac4d3-0f99-4f60-8bdc-533fad468227)

**Comment by abuduvision** [comment]
![53b12229379ef5c4608139ce8158cda](https://github.com/strike-digital/node_pie/assets/142294846/3efc5586-1caa-4dda-8ae7-818a9e0aeefe)
hi！
It was all fine when I used it for the first time. But then I changed the setting of “expand node group”, there is something got wrong. Even though I reloaded the plugin it won't work

**Comment by strike-digital** [comment]
Ok, It's been a while, but I got around to fixing this in the latest release. It's not really a fix so much as a workaround, but the addon should work on MacOS now.

@abuduvision your problem should be fixed in the latest release as well.
