### ISSUE TITLE
erorr in shading editor on 4.0 alpha

### ISSUE THREAD

**Issue by wxz-site** [strike-digital/node_pie#22]

**Comment by wxz-site** [comment]
<img width="719" alt="Snipaste_2023-09-26_22-39-24" src="https://github.com/strike-digital/node_pie/assets/53850249/f2f62298-fe86-46b8-8b3b-31b1a169da90">
<img width="879" alt="Snipaste_2023-09-26_22-39-59" src="https://github.com/strike-digital/node_pie/assets/53850249/64975893-c0a5-4695-a022-c2e206b63f1a">

**Comment by wxz-site** [comment]
<img width="1264" alt="Snipaste_2023-09-26_22-42-42" src="https://github.com/strike-digital/node_pie/assets/53850249/ddf5c4c7-6543-4699-a926-ecd79c8f90e9">
on geo nodes editor, like debug log on the left

**Comment by strike-digital** [comment]
Hi sorry for the wait, this should be fixed in the latest release

**Comment by wxz-site** [comment]
Thanks for your contributions!😋
