### ISSUE TITLE
Blender 4.1 Support / Only Working With Shader Editor / Category Color

### ISSUE THREAD

**Issue by VeissieV** [strike-digital/node_pie#24]
Hello, I can't seem to get the pie menu to pop up in any other editor than the shader editor. Is it working in 4.1 for for anyone else?

I was also hoping it would be possible to add dedicated color/theme entries to the addon since most of the category colors are incorrect for me because I'm using a custom Blender theme. It'd be even better if these were customizable in the addon preferences.

Thanks, this addon is already better/easier on the eyes than the similar Alt Tab addon and the additional non node items like search and node groups are nice.

**Comment by strike-digital** [comment]
Hi, sorry for the wait, I've uploaded a few new versions, can you try the latest one and see if the problems have been fixed?

About the different colours, that's interesting as the way the addon shows the colours, they should automatically update with the preferences colours. Could you send a screenshot of the colours in the preferences, and also the colours on the pie menu?

Thanks!
