### ISSUE TITLE
Socket drag add

### ISSUE THREAD

**Issue by KristjanLaane** [strike-digital/node_pie#26]
it would be great to support using node pie from socket drag:
![image](https://github.com/strike-digital/node_pie/assets/1708294/c83dd333-5b1e-4f58-a214-ed21ee8ebcdc)

currently the Blender native add search box shows up:
![image](https://github.com/strike-digital/node_pie/assets/1708294/1ee19e55-185f-4813-9a0f-b2868f1b94b7)

im aware that link drag exists, but that is not the same thing
thank you for making useful stuff!

**Comment by strike-digital** [comment]
Hi, unfortunately it's not possible to replace the socket drag menu directly, it's just one of the limitations of the API.

I'm not too how link drag is that different, though, other than having to press control before dragging?

**Comment by strike-digital** [comment]
Ah right, that is something different. Currently, if you control click and drag on a socket, you should be able to get the functionality you want:


https://github.com/strike-digital/node_pie/assets/59890307/9c7492ec-7416-450a-8a9d-61ef69b8d2ac

**Comment by KristjanLaane** [comment]
i discovered that the reason it did not work is because i had changed my node pie shortcut to just RMB:
![image](https://github.com/strike-digital/node_pie/assets/1708294/af6bf78c-1419-41b2-bb7e-71c682fd2131)

normal add works then but socket drag does not. when i changed teh shortcut back to the default of Ctrl LMB then socket drag started to work as well.
the reason i do not like the original shortcut is because it messes up an already existing shortcut of changing output socket of an existing link. For example, in order to change the output connection going out from Fac to going out from Color i need to hold down Control and use LMB to unconnect from Fac:
![image](https://github.com/strike-digital/node_pie/assets/1708294/86e2c06c-8aee-42fc-a0bd-eaf1a06587c3)

![image](https://github.com/strike-digital/node_pie/assets/1708294/5ef9e6cb-1a10-47ef-890c-193dfd3769d4)
 But with node pie default shortcut this stops working completely (and i spent hours some time ago figuring out why it is not working)
I found another solution now, i changed the socket changing shortcut to Alt LMB and left the node pie shortcut to oringial Ctrl LMB so i could do the socket drag. 
it all works now. thanks!
