### ISSUE TITLE
socket intelligence

### ISSUE THREAD

**Issue by KristjanLaane** [strike-digital/node_pie#27]
when using socket drag, would it be possible to automagically filter the nodes that are shown to be only those compatible with the output socket i drag from. for instance, only show nodes here that have at least one input socket that accepts a Mesh type input:
![image](https://github.com/strike-digital/node_pie/assets/1708294/65455e4d-c3ac-45ad-8840-7e72d0c7be54)
basically remove the clutter by having a fluid UI that excludes invalid nodes that could not be used for sure / that are not relevant at all for the connection to be made.
this feature would be not just very useful, but create a sense of awe :)

**Comment by strike-digital** [comment]
That's a good idea, I've thought about it before, so I gave it a shot:

https://github.com/strike-digital/node_pie/assets/59890307/085c5f97-b997-4f72-b2b7-060e2fc0580f

[node_pie_1_2_31.zip](https://github.com/user-attachments/files/15567228/node_pie_1_2_31.zip)

Here's the build, I'd be interested to know what you think? I did try it with removing invalid buttons all together, but it completely changed the shape of the pie menu and destroyed any muscle memory, so I settled for just greying them out.

**Comment by KristjanLaane** [comment]
it is fantastic, wow!
(would be nice to make the popularity of all the grayed out nodes to be minimal size, too)

**Comment by strike-digital** [comment]
Good idea, I've added that and uploaded a new release 👍
https://github.com/strike-digital/node_pie/releases/tag/1.2.31

**Comment by KristjanLaane** [comment]
you are fast!
