### ISSUE TITLE
There is a little bug with localization

### ISSUE THREAD

**Issue by JimWho** [strike-digital/node_pie#4]
Almost all words are localized for these languages in blender, and there is a little bug in node pie that just some words are translated automatically
![image](https://user-images.githubusercontent.com/87781679/188316469-1b2aa067-d18c-4aa3-924b-33b7b0e4fa55.png)
![image](https://user-images.githubusercontent.com/87781679/188316723-e3aba024-b141-4eb2-a569-025ffd1db9c1.png)
So I think maybe when the inference selection is true, "texture" and “bsdf” dont remove, and use
      bpy.app.translations.pgettext(text)
to translate. This is just my rough understanding of blender API
![image](https://user-images.githubusercontent.com/87781679/188316876-f202edec-9b05-4a7d-a9f4-a2322c1ba285.png)

**Comment by strike-digital** [comment]
Ah, sorry, I didn't see this, it should now be fixed in the latest update :)
