### ISSUE TITLE
Wrong pie in nested groups!

### ISSUE THREAD

**Issue by FidoAnh** [strike-digital/node_pie#6]
Something wrong when I used addon in the nested group
![Capture](https://user-images.githubusercontent.com/103020170/200099510-8e1e4500-e497-481a-ba69-ca54041fdbf8.PNG)
![Capture1](https://user-images.githubusercontent.com/103020170/200099514-df648db3-0409-47a3-a12c-8ee742787a88.PNG)
![Capture2](https://user-images.githubusercontent.com/103020170/200099516-e89ccdfe-324a-4439-9eaf-43dbfa071551.PNG)

**Comment by strike-digital** [comment]
Huh, that's weird, I can't seem to replicate the problem, can you try looking in the terminal (Top bar > Window > Toggle system console) and see if there are any errors there?

**Comment by FidoAnh** [comment]
This is my console!
![Capture3](https://user-images.githubusercontent.com/103020170/200147728-73a9e1f5-8693-4d4a-a803-ff0c9d9d62f1.PNG)

**Comment by FidoAnh** [comment]
Today even in first group I create for test:((
![Capture4](https://user-images.githubusercontent.com/103020170/200148169-6313b2ef-bf19-4e9e-8e18-f167da945a19.PNG)
![Capture5](https://user-images.githubusercontent.com/103020170/200148175-7d043dca-7517-46dd-adf0-9cbf960f21f2.PNG)
![Capture6](https://user-images.githubusercontent.com/103020170/200148180-e9a0ad8f-1eee-452b-9070-f07899428193.PNG)

**Comment by nurb2kea** [comment]
Just for info, maybe helps.
I'm on latest macOS 13 Ventura & blender 3.5 alpha & Node Pie 1.2.1
For me it's working in all node editors incl. shader-world. 
When I create a node group and 2. node group, it's also fully working in all node editors.
And it behaves the same with 3.2.1 , 3.3.1 , 3.4 ...

**Comment by strike-digital** [comment]
Hmm, thanks for the info, can you try downloading the latest release and seeing if that works?
Thanks

**Comment by nurb2kea** [comment]
What latest release? Did you mean me?

**Comment by strike-digital** [comment]
Ah, no, sorry, I meant @FidoAnh :)

**Comment by FidoAnh** [comment]
Still wrong in something...
![Capture1](https://user-images.githubusercontent.com/103020170/200201558-fadfff3d-06f8-43e0-88cc-a1fc00b40265.PNG)
![Capture](https://user-images.githubusercontent.com/103020170/200201544-fbe992da-e248-4b77-b1ad-855c7feada99.PNG)
![Capture2](https://user-images.githubusercontent.com/103020170/200201648-907d4125-7e5c-44e0-a060-9131c9a0fc2b.PNG)

**Comment by FidoAnh** [comment]
My Geometry node broken even not in a group. I think they can't get NodeGroups.
![Capture3](https://user-images.githubusercontent.com/103020170/200202331-304c8b8d-8c7a-46bb-b0bd-1567b8fb2d6f.PNG)
![Capture4](https://user-images.githubusercontent.com/103020170/200202333-75290dae-5067-478a-a32c-54f8867dffb7.PNG)

**Comment by nurb2kea** [comment]
What blender 3.3.1 version do you use. The downloaded version via blender.org or do you install it via steam or do you compile your blender yourself...?
Also what windows version you're using?
Did you uninstall the 1.1.1 Node Pie first and restart blender to install Node Pie 1.2.2?

**Comment by FidoAnh** [comment]
Thanks @nurb2kea but factory settings don't work!

**Comment by strike-digital** [comment]
I think this should be fixed now, can you try out the latest release and see if it works?

**Comment by FidoAnh** [comment]
@strike-digital Thank you so much! It work perfectly!
